version: 2
references:
  build_and_deploy: &build_and_deploy
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: install dependencies
          command: |
            sudo pip install awscli
            curl -LO https://github.com/kubernetes/kops/releases/download/1.9.1/kops-linux-amd64
            sudo chmod +x kops-linux-amd64
            sudo mv kops-linux-amd64 /usr/bin/kops
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            sudo chmod +x kubectl
            sudo mv kubectl /usr/bin
            sudo apt-get install gettext-base
      - run:
          name: build, push & deploy
          command: |
            export ROLE_ARN=arn:aws:iam::$ACCOUNT_ID:role/KubernetesDevelopers
            export REPO=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
            docker build -t $REPO/$CIRCLE_PROJECT_REPONAME:${CIRCLE_SHA1} .
            CREDENTIALS="$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name build-$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM | jq '.Credentials')"
            export AWS_ACCESS_KEY_ID="$(echo $CREDENTIALS | jq -r '.AccessKeyId')"
            export AWS_SECRET_ACCESS_KEY="$(echo $CREDENTIALS | jq -r '.SecretAccessKey')"
            export AWS_SESSION_TOKEN="$(echo $CREDENTIALS | jq -r '.SessionToken')"
            eval $(aws ecr get-login --region us-east-1 --no-include-email)
            docker push $REPO/$CIRCLE_PROJECT_REPONAME:${CIRCLE_SHA1}
            export KOPS_STATE_STORE=s3://airswap-kubernetes-$ENV
            kops export kubecfg kubernetes.$ENV.airswap.io
            envsubst < kube.template.yml > kube.yml
            kubectl apply -f kube.yml
jobs:
  build_and_deploy:
    <<: *build_and_deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          context: Development
          filters:
            branches:
              only:
                - develop